# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

db_index <- function(ip, ip_from) {
    .Call(`_carmen_db_index`, ip, ip_from)
}

